apiVersion: v1
data:
  password: cHdkMCo=
  username: ZGJ1c2VyMA==
kind: Secret
metadata:
  name: postgres0.creds
  namespace: python-crud-api
type: string
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: postgres0
  name: postgres0
  namespace: python-crud-api
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    run: postgres0
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: pycrudapi
  name: pycrudapi
  namespace: python-crud-api
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: pycrudapi
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: postgres0
  name: postgres0
  namespace: python-crud-api
spec:
  replicas: 1
  selector:
    matchLabels:
      run: postgres0
  template:
    metadata:
      labels:
        run: postgres0
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: titanicdb
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: postgres0.creds
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres0.creds
        image: ghcr.io/longwuyuan/python-crud-api-postgres0:main-948e4de
        imagePullPolicy: IfNotPresent
        name: postgres0
        ports:
        - containerPort: 5432
          protocol: TCP
        resources: {}
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: pycrudapi
  name: pycrudapi
  namespace: python-crud-api
spec:
  replicas: 1
  selector:
    matchLabels:
      run: pycrudapi
  template:
    metadata:
      labels:
        run: pycrudapi
    spec:
      containers:
      - image: ghcr.io/longwuyuan/python-crud-api:main-17c244f
        imagePullPolicy: IfNotPresent
        name: pycrudapi
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
      restartPolicy: Always
