name: Docker Image CI

on:
  push:
    paths:
      - 'src/pycrudapi/**'

  pull_request:
    paths:
      - 'src/pycrudapi/**'

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Login to registry(ghcr.io)
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set output
        id: get_branchname
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Add branchname to image_name
        id: add_branchname
        env:
          IMAGE_NAME: ${{ github.repository }}/${{ steps.get_branchname.outputs.short_ref }}

      - name: Build pycrudapi image and push to ghcr.io
        uses: docker/build-push-action@v2
        with:
          context: ./src/pycrudapi
          tags: ${{ github.sha }}
          push: true

      - name: Setup Kubectl Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "4.4.0"

      - name: Update Kubernetes resources with kubectl kustomize
        env:
          NEW_TAG: $GITHUB_SHA
        run: |
          cd src/kubernetes/base
          sed -i "s/newTag:.*/newTag: $NEW_TAG/" kustomization.yaml
          kubectl kustomize ./ | tee ../../../install/python-crud-api.yaml
        
      - name: Commit files and changes
        run: |
          git config --local user.email "longwuyuan@gmail.com"
          git config --local user.name "longwuyuan"
          git add -A
          git commit -am "Bump app version"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GHCR_PAT }}
          branch: ${{ github.ref }}
