name: Create and publish pycrudapi Docker image and K8s manifest

on:
  push:
    paths:
      - 'src/pycrudapi/**'

  pull_request:
    paths:
      - 'src/pycrudapi/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image-and-manifest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false 
          fetch-depth: 0

      - name: Log in to ghcr.io
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=sha,prefix={{branch}}-

      - name: Build and push Docker image
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: ./src/pycrudapi
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Setup Kubectl Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "4.4.0"

      - name: Update K8S manifests
        env:
          FULL_IMAGE_NAME: ${{ steps.meta.outputs.tags }}
        run: |
          cd src/kubernetes/base
          NEW_TAG=`echo $FULL_IMAGE_NAME | cut -f2 -d":"`
          sed -i "s|newTag:.*|newTag: $NEW_TAG|" kustomization.yaml
          kubectl kustomize ./ > ../../../install/pycrudapi.yaml
          git config --local user.email "longwuyuan@gmail.com"
          git config --local user.name "longwuyuan"
          git add -A
          COMMIT_MSG="Change pycrudapi image tag to $NEW_TAG"
          git commit -m "$COMMIT_MSG"

      - name: Push updated K8S manifests
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GHCR_PAT }}
          branch: ${{ github.ref }}
